apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-cc
  namespace: default
  labels:
    app: kube-cc
spec:
  selector:
    matchLabels:
      app: kube-cc
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kube-cc
    spec:    
      containers:
        - name: client
          image: sgfoot/kube-box:0.5.0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
              name: client
        - name: backend
          image: sgfoot/kube-box:0.5.0
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
              name: backend
      restartPolicy: Always
