apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-cc
  namespace: default
  labels:
    app: kube-cc
spec:
  selector:
    matchLabels:
      app: kube-cc
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kube-cc
    spec:    
      containers:
        - name: client
          image: sgfoot/kube-box:0.5.0
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 80
              name: client
        - name: backend
          image: sgfoot/kube-box:0.5.0
          env:
            - name: PORT
              value: "8080"
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 8080
              name: backend
      restartPolicy: Always

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: MYAPP
  namespace: default
  labels:
    app: MYAPP
spec:
  selector:
    matchLabels:
      app: MYAPP
  template:
    metadata:
      labels:
        app: MYAPP
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: MYAPP
        image: debian
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
      terminationGracePeriodSeconds: 30
      volumes:
      - name: localtime
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai