name: check-script by k1s
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  sh-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run the sh-checker
        uses: luizm/action-sh-checker@latest
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Optional if sh_checker_comment is false.
        #   SHELLCHECK_OPTS: -e SC1004 # Optional: exclude some shellcheck warnings.
        #   SHFMT_OPTS: -s # Optional: pass arguments to shfmt.
        # with:
        #   sh_checker_comment: true
        #   sh_checker_exclude: ".terraform ^dir/example.sh"
